"""empty message

Revision ID: 41b5fe20ee98
Revises: 3b7a084d0c68
Create Date: 2024-03-06 16:02:54.187790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41b5fe20ee98'
down_revision = '3b7a084d0c68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_data', schema=None) as batch_op:
        batch_op.drop_column('img_id')

    # ### end Alembic commands ###
