"""empty message

Revision ID: e3ebb4cd3aab
Revises: 4cf4c2b2bddd
Create Date: 2024-03-04 13:08:20.281802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ebb4cd3aab'
down_revision = '4cf4c2b2bddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('image_collection_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('data_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('data_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('image_collection_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
